---
- name: Zookeeper Status Finding
  hosts: zookeeper
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: variables

    - name: Check if Zookeeper Service Running
      shell: "systemctl show -p SubState {{zookeeper_service_name}}"
      changed_when: false
      # On some SELinux enabled hosts this command will error out, handled in next set_fact task
      failed_when: false
      check_mode: false
      register: substate

    - set_fact:
        install_pattern: "{{ 'parallel' if substate.stdout != 'SubState=running' or substate.rc == 1 or zookeeper_deployment_strategy == 'parallel' else 'serial' }}"

    - name: "Group Hosts by Installation Pattern: Parallel or Serial"
      group_by:
        key: zookeeper_{{install_pattern}}
      changed_when: false

- name: Zookeeper Parallel Provisioning
  hosts: zookeeper_parallel
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: zookeeper

- name: Zookeeper Serial Ordering
  hosts: zookeeper_serial
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: zookeeper
        tasks_from: dynamic_groups.yml

- name: Zookeeper Followers Provisioning
  hosts: zookeeper_follower
  serial: 1
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: zookeeper

    - name: Proceed Prompt
      pause:
        prompt: "Press Enter to Proceed to Next Node. Ctrl + C to Abort"
      when: zookeeper_pause_rolling_deployment|bool

- name: Zookeeper Leader Provisioning
  hosts: zookeeper_leader
  gather_facts: false
  tags: zookeeper
  environment: "{{ proxy_env }}"
  tasks:
    - import_role:
        name: zookeeper

    - name: Proceed Prompt
      pause:
        prompt: "Press Enter to Proceed to Next Node. Ctrl + C to Abort"
      when: zookeeper_pause_rolling_deployment|bool
