---
- name: Create Directory on Controller for Host Error Files
  file:
    state: directory
    path: "error_files/{{inventory_hostname}}"
  delegate_to: localhost
  vars:
    ansible_connection: local
    ansible_become: false

- name: Register all Log Files
  find:
    paths: "{{log_dir}}"
    recurse: false
  register: find_output

- name: Fetch Config and Log Files
  fetch:
    dest: "error_files/{{inventory_hostname}}/"
    src: "{{ item }}"
    flat: true
  loop: "{{ find_output.files | map(attribute='path') | list + [config_file] }}"

- name: Fail Installation
  fail:
    msg: Health checks failed. Review log and property files in error_files/ directory
